!conda install -y scipy numpy pygame jupyter

Utils

In [78]:
from scipy.io import loadmat
import numpy as np
import pygame

pygame.init()
font = pygame.font.Font(None, 36)

def load_data(file_name):
    # Load the .mat file
    data = loadmat(file_name)
    # Display the contents
    return data

def upsample_fractional(signal, factor):
    """
    Upsample a 2D signal by a given factor using linear interpolation.
    Each row is assumed to be a separate channel or variable, and columns represent time.

    :param signal: Input 2D signal as a numpy array (channels x time)
    :param factor: Upsampling factor (can be integer or float)
    :return: Upsampled 2D signal
    """
    # Get the original dimensions
    num_channels, original_time = signal.shape

    # Calculate the new time dimension
    new_time = int(original_time * factor)

    # Create old and new time axes
    old_time_indices = np.arange(original_time)
    new_time_indices = np.linspace(0, original_time - 1, new_time)

    # Initialize the output array
    upsampled_signal = np.zeros((num_channels, new_time))

    # Interpolate each channel
    for channel in range(num_channels):
        upsampled_signal[channel, :] = np.interp(
            new_time_indices, old_time_indices, signal[channel, :])

    return upsampled_signal

def get_color(value):
    value = min(value, 1)
    value = max(value, 0)
    # Example color mapping function
    return int(value * 255), 0, 255 - int(value * 255)

def viz_glove(screen, glove_data):
    left = 150
    top = 50
    scale = 3
    size = 5

    def viz_glove_helper(screen, x, y, data):
        pygame.draw.rect(screen, get_color(data), (scale*x+left, scale*y+top, scale*size, scale*size))
    
    """
    (0, 'Thumb_Roll     ')
    (1, 'Thumb_Inner    ')
    (2, 'Thumb_Outer    ')
    (3, 'TI_Abduction   ')
    (4, 'Index_Inner    ')
    (5, 'Index_Middle   ')
    (6, 'Middle_Inner   ')
    (7, 'Middle_Middle  ')
    (8, 'MI_Abduction   ')
    (9, 'Ring_Inner     ')
    (10, 'Ring_Middle    ')
    (11, 'RM_Abduction   ')
    (12, 'Pinky_Inner    ')
    (13, 'Pinky_Middle   ')
    (14, 'PR_Abduction   ')
    (15, 'Palm_Arch      ')
    (16, 'Wrist_Flex     ')
    (17, 'Wrist_Abduction')
    """
    
    viz_glove_helper(screen, 15, 45, glove_data[ 0])
    viz_glove_helper(screen,  5, 35, glove_data[ 1])
    viz_glove_helper(screen,  5, 25, glove_data[ 2])
    viz_glove_helper(screen, 15, 35, glove_data[ 3])
    viz_glove_helper(screen, 15, 15, glove_data[ 4])
    viz_glove_helper(screen, 15,  5, glove_data[ 5])
    viz_glove_helper(screen, 25, 15, glove_data[ 6])
    
    viz_glove_helper(screen, 25,  5, glove_data[ 7])
    viz_glove_helper(screen, 20, 25, glove_data[ 8])
    viz_glove_helper(screen, 35, 15, glove_data[ 9])
    viz_glove_helper(screen, 35,  5, glove_data[10])
    viz_glove_helper(screen, 30, 25, glove_data[11])
    viz_glove_helper(screen, 45, 15, glove_data[12])
    viz_glove_helper(screen, 45,  5, glove_data[13])
    viz_glove_helper(screen, 40, 25, glove_data[14])
    
    viz_glove_helper(screen, 25, 35, glove_data[15])
    viz_glove_helper(screen, 30, 35, glove_data[15])
    viz_glove_helper(screen, 35, 35, glove_data[15])
    viz_glove_helper(screen, 40, 35, glove_data[15])
    
    viz_glove_helper(screen, 25, 45, glove_data[16])
    viz_glove_helper(screen, 35, 45, glove_data[17])
    
    screen.blit(font.render(f"Glove", True, (200, 200, 200)), (left+scale*15, top+scale*55))

def viz_glove_legend(screen):  
    left = 450
    top = 130
    text = font.render(f"0", True, (255, 255, 255))
    screen.blit(text, (left, top))
    pygame.draw.rect(screen, get_color(0), (left+50, top, 25, 25))
    pygame.draw.rect(screen, get_color(0.25), (left+75, top, 25, 25))
    pygame.draw.rect(screen, get_color(0.5), (left+100, top, 25, 25))
    pygame.draw.rect(screen, get_color(0.75), (left+125, top, 25, 25))
    pygame.draw.rect(screen, get_color(1), (left+150, top, 25, 25))
    text = font.render(f"1", True, (255, 255, 255))
    screen.blit(text, (left+200, top))
    
def viz_emg(screen, emg_frame):
    left = 100
    top = 300
    scale = 20
    size = 1
    
    for i in range(9):
        for j in range(14):
            pygame.draw.rect(screen, get_color(emg_frame[i*j]), (scale*j+left, scale*i+top, scale*size, scale*size))
    
    screen.blit(font.render(f"Anterior HD-sEMG", True, (200, 200, 200)), (left+scale*1, top+scale*10))
    
    def viz_emg_extensor_helper(screen, x, y, data):
        pygame.draw.rect(screen, get_color(data), (scale*x+left+scale*size*14+120, scale*y+top+10, scale*size*1, scale*size*1))

    viz_emg_extensor_helper(screen, 5, 1, emg_frame[126])
    viz_emg_extensor_helper(screen, 5, 3, emg_frame[127])
    viz_emg_extensor_helper(screen, 5, 5, emg_frame[128])
    viz_emg_extensor_helper(screen, 3, 1, emg_frame[129])
    viz_emg_extensor_helper(screen, 3, 3, emg_frame[130])
    viz_emg_extensor_helper(screen, 3, 5, emg_frame[131])
    viz_emg_extensor_helper(screen, 1, 2, emg_frame[132])
    viz_emg_extensor_helper(screen, 1, 4, emg_frame[133]) 
    
    screen.blit(font.render(f"Extrinsic Mono electrodes", True, (200, 200, 200)), (left+scale*size*14+50, top+scale*10))

    

Load a file and print out the raw data
Download files from: https://osf.io/wa3qk/

In [79]:
data = load_data('data/subj11/detop_exp01_subj11_Sess1_01_01.mat') # Load a .mat of your choice
print(data)

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Tue Oct 20 09:19:25 2020', '__version__': '1.0', '__globals__': [], 'fs_emg': array([[2048.]]), 'glove': array([[0.25555557, 0.25555557, 0.25555557, ..., 0.6       , 0.6       ,
        0.6       ],
       [0.3602941 , 0.3602941 , 0.3602941 , ..., 0.30147058, 0.30147058,
        0.30147058],
       [0.31707317, 0.31707317, 0.31707317, ..., 0.17073171, 0.17073171,
        0.17073171],
       ...,
       [0.7184466 , 0.7184466 , 0.7184466 , ..., 0.63106793, 0.63106793,
        0.63106793],
       [0.94736844, 0.94736844, 0.94736844, ..., 1.1052631 , 1.1052631 ,
        1.1052631 ],
       [0.        , 0.        , 0.        , ..., 0.27272728, 0.27272728,
        0.27272728]], dtype=float32), 'subject': array(['subj11'], dtype='<U6'), 'date': array(['20170627'], dtype='<U8'), 'speed': array(['fast'], dtype='<U4'), 'fs_glove': array([[256.]]), 'channels_glove': array(['Thumb_Roll     ', 'Thumb_Inner    ', 'Thumb_Outer    ',
 

Sample the data to a frequency

In [80]:
fps = 100 # select the fps to sample to

emg_hz = data['fs_emg'][0]
glove_hz = data['fs_glove'][0]
emg_raw = np.array(upsample_fractional(data['emg'], fps/emg_hz))
glove = np.array(upsample_fractional(data['glove'], fps/glove_hz))
num_frames = max(emg_raw.shape[-1], glove.shape[-1])
print("emg.shape:"+str(emg_raw.shape))
print("glove.shape:"+str(glove.shape))
print("frames:"+str(num_frames))

emg.shape:(134, 162)
glove.shape:(18, 162)
frames:162


C:\Users\Dhruv\AppData\Local\Temp\ipykernel_3084\1448338358.py:27: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  new_time = int(original_time * factor)


Glove data is normalized to [0,1]
EMG data is a bit over the place, analyze it and map it to [0,1]

In [81]:
emg_hdsmg = emg_raw[:125, ...]
emg_hdsmg = emg_hdsmg - np.mean(emg_hdsmg[:, 0:100], axis=1, keepdims=True)

emg_hdsmg_min = np.min(emg_hdsmg, keepdims=True)
emg_hdsmg_max = np.max(emg_hdsmg, keepdims=True)
emg_hdsmg_range = emg_hdsmg_max - emg_hdsmg_min
emg_hdsmg = (emg_hdsmg - emg_hdsmg_min) / emg_hdsmg_range

emg_mono = emg_raw[125:, ...]
emg_mono_min = np.min(emg_mono, axis=1, keepdims=True)
emg_mono_max = np.max(emg_mono, axis=1, keepdims=True)
emg_mono_range = emg_mono_max - emg_mono_min
emg_mono = (emg_mono - emg_mono_min) / emg_mono_range

emg = np.concat([emg_hdsmg, emg_mono], axis=0)
print(emg.shape)


(134, 162)


In [82]:
np.max(emg, axis=1)

array([0.61473475, 0.63353841, 0.64138309, 0.63293167, 0.63705789,
       0.61308671, 0.62650709, 0.65591357, 0.68451235, 0.61022487,
       0.6226438 , 0.60871007, 0.59995415, 0.61172141, 0.59625506,
       0.6154937 , 0.62952083, 0.67455856, 0.60385385, 0.60710119,
       0.5870778 , 0.56049891, 0.5740846 , 0.60401298, 0.56298951,
       0.59400106, 0.61403385, 0.58952563, 0.57697854, 0.55027472,
       0.54609781, 0.55437112, 0.54515194, 0.55163077, 0.56769374,
       0.62094169, 0.59387933, 0.54080723, 0.49078546, 0.47956771,
       0.49326528, 0.5191427 , 0.53713595, 0.55222352, 0.60196116,
       0.50978866, 0.47314482, 0.45960747, 0.44981136, 0.45407809,
       0.47919197, 0.5074749 , 0.52102261, 0.56271607, 0.48789843,
       0.45408282, 0.42079912, 0.41878232, 0.43309663, 0.44288055,
       0.47506085, 0.48827583, 0.51798459, 0.47576008, 0.44762527,
       0.44296875, 0.42416591, 0.41292285, 0.41985992, 0.44445942,
       0.44903843, 0.47311668, 0.51660723, 0.48875929, 0.48868

Visualize

In [83]:
class EmgKinVisualizer:
    def __init__(self, width=800, height=600):
        self.speed = 1
        self.width = width
        self.height = height
        self.current_frame = 0
        self.running = False

        self.screen = pygame.display.set_mode(
            (width, height + 50))  # Extra height for timeline
        pygame.display.set_caption("EMG and Kinematics Visualizer")

        self.timeline_rect = pygame.Rect(50, height + 10, width - 100, 30)
        self.slider_rect = pygame.Rect(50, height + 10, 10, 30)
        self.exit_button_rect = pygame.Rect(10, 10, 60, 30)



    def run(self):
        clock = pygame.time.Clock()

        while True:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    return
                elif event.type == pygame.KEYDOWN:
                    self.handle_key_event(event.key)
                elif event.type == pygame.MOUSEBUTTONDOWN:
                    if event.button == 1:  # Left mouse button
                        if self.timeline_rect.collidepoint(event.pos):
                            self.update_frame_from_mouse(event.pos[0])
                        if self.exit_button_rect.collidepoint(event.pos):
                            pygame.quit()
                            return
                elif event.type == pygame.MOUSEMOTION:
                    if event.buttons[0]:  # Left mouse button held down
                        if self.timeline_rect.collidepoint(event.pos):
                            self.update_frame_from_mouse(event.pos[0])

            if self.running:
                self.current_frame += self.speed
                if self.current_frame >= num_frames:
                    self.current_frame = 0
                elif self.current_frame < 0:
                    self.current_frame = num_frames - 1

            self.draw()
            pygame.display.flip()
            clock.tick(fps/3)

    def draw(self):
        self.screen.fill((0, 0, 0))
        
        # Draw glove data
        viz_glove(self.screen, glove[:, self.current_frame])
        viz_glove_legend(self.screen)
        
        # Draw emg data
        viz_emg(self.screen, emg[:, self.current_frame])

        # Draw timeline
        pygame.draw.rect(self.screen, (100, 100, 100), self.timeline_rect)
        slider_x = int(self.timeline_rect.left +
                       (self.current_frame / num_frames) * self.timeline_rect.width)
        self.slider_rect.left = slider_x
        pygame.draw.rect(self.screen, (200, 200, 200), self.slider_rect)

        # Draw current frame number
        text = font.render(
            f"Frame: {self.current_frame}/{num_frames-1}", True, (200, 200, 200))
        self.screen.blit(text, (10, self.height - 30))

        # Draw exit button
        pygame.draw.rect(self.screen, (200, 50, 50), self.exit_button_rect)
        exit_text = font.render("Exit", True, (255, 255, 255))
        self.screen.blit(exit_text, (self.exit_button_rect.x + 10, self.exit_button_rect.y + 5))

    def handle_key_event(self, key):
        if key == pygame.K_SPACE:
            self.running = not self.running
        elif key == pygame.K_RIGHT:
            self.speed = 1
            self.running = True
        elif key == pygame.K_LEFT:
            self.speed = -1
            self.running = True
        elif key == pygame.K_UP:
            self.speed = min(self.speed * 2, 16)
        elif key == pygame.K_DOWN:
            self.speed = max(self.speed // 2, 1)

    def update_frame_from_mouse(self, mouse_x):
        timeline_x = mouse_x - self.timeline_rect.left
        frame_ratio = timeline_x / self.timeline_rect.width
        self.current_frame = int(frame_ratio * num_frames)
        self.current_frame = max(0, min(self.current_frame, num_frames - 1))
        self.running = False


if __name__ == "__main__":
    visualizer = EmgKinVisualizer()
    visualizer.run()

In [84]:
print(min(min(row) for row in emg[0:125]))
print(max(max(row) for row in emg[0:125]))

print(min(min(row) for row in emg[126:]))
print(max(max(row) for row in emg[126:]))

print((emg.shape))


0.0
1.0
0.0
1.0
(134, 162)


In [85]:
print(emg[0:125])

[[0.38938388 0.38951811 0.33180019 ... 0.37741415 0.41885382 0.42533307]
 [0.39395512 0.38738884 0.32695912 ... 0.36848413 0.4095193  0.42494424]
 [0.39894162 0.38958923 0.31450248 ... 0.37801815 0.4234073  0.43050383]
 ...
 [0.35962113 0.36743182 0.49645661 ... 0.385064   0.33374355 0.31910407]
 [0.35590504 0.36435367 0.50227518 ... 0.38165498 0.34466402 0.317385  ]
 [0.35329606 0.3726147  0.50003024 ... 0.37778806 0.34428455 0.32447593]]
